name: Deploy Benchmark Results to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  benchmark-and-deploy:
    name: Run Benchmarks and Deploy to Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build pkg-config
        python -m pip install --upgrade pip
        pip install meson
        
    - name: Configure build (Release)
      run: |
        meson setup builddir --buildtype=release
        
    - name: Build project
      run: |
        meson compile -C builddir
        
    - name: Run benchmarks with JSON output
      run: |
        ./builddir/bench_almo --benchmark_format=json --benchmark_out=benchmark_result.json --benchmark_min_time=0.5s
        
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Almo C++ Performance Benchmarks
        tool: 'googlecpp'
        output-file-path: benchmark_result.json
        # Store the data in gh-pages branch
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        # Deploy to GitHub Pages
        gh-pages-branch: gh-pages
        benchmark-data-dir-path: dev/bench
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: false
        # Enable additional features
        summary-always: true
        max-items-in-chart: 50
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './benchmark-data'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2