name: Release for all platforms
on:
  release:
    types: [published]
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build for Release
        run: make build
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/almo
          asset_name: ${{ matrix.os }}
          asset_content_type: application/octet-stream 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}